# Generated by Django 4.1.2 on 2022-10-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professor',
            field=models.BooleanField(default=False),
        ),
    ]
