# Generated by Django 4.1.2 on 2022-10-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.JSONField(null=True),
        ),
    ]
