# Generated by Django 4.1.2 on 2022-11-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_courses_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='logoutTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totalDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
