# Generated by Django 4.1.2 on 2022-10-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_title_course_cdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='cdescription',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='ctitle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
