# Generated by Django 4.1.2 on 2022-10-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_section_alter_course_cdescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section',
            new_name='nameofsection',
        ),
    ]
