# Generated by Django 4.1.2 on 2022-10-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_csection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='csection',
        ),
        migrations.AddField(
            model_name='course',
            name='clesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
    ]
