# Generated by Django 4.1.2 on 2022-10-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_remove_course_csection_course_clesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='clesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
    ]
