# Generated by Django 4.1.2 on 2022-10-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_ccreator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ccreator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='ctitle',
            new_name='title',
        ),
    ]
