# Generated by Django 4.1.2 on 2022-10-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_ccreator_course_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
