# Generated by Django 4.1.2 on 2022-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_lesson_course_course_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='key',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
