# Generated by Django 4.1.2 on 2022-11-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_students_alter_course_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
