# Generated by Django 4.1.2 on 2022-11-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_delete_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(default='', max_length=20),
        ),
    ]
