# Generated by Django 4.1.2 on 2022-11-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_feedback_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_course',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_date',
        ),
    ]
