# Generated by Django 4.1.2 on 2022-11-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_remove_feedback_feedback_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='feedbacks',
            field=models.ManyToManyField(to='courses.feedback'),
        ),
    ]
