# Generated by Django 4.1.2 on 2022-11-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_course_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_creator',
        ),
    ]
