# Generated by Django 4.1.2 on 2022-11-08 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0028_remove_feedback_feedback_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
